// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8LhjYHgce4iaXMxvzoDYD8D_N4XPUwaM',
    appId: '1:926948973737:web:122690445c51e3e5daddb8',
    messagingSenderId: '926948973737',
    projectId: 'history-950d8',
    authDomain: 'history-950d8.firebaseapp.com',
    storageBucket: 'history-950d8.firebasestorage.app',
    measurementId: 'G-JDZFXG7W31',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcq9O59xmM6u2qzS0voWnjcethGZC9zdw',
    appId: '1:926948973737:android:7b5380741693574cdaddb8',
    messagingSenderId: '926948973737',
    projectId: 'history-950d8',
    storageBucket: 'history-950d8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-6Yo8oIP_e5QMC9yK256iEv5HzlQNbIE',
    appId: '1:926948973737:ios:e037e6e2c72e3ca0daddb8',
    messagingSenderId: '926948973737',
    projectId: 'history-950d8',
    storageBucket: 'history-950d8.firebasestorage.app',
    iosBundleId: 'com.example.whatsappClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-6Yo8oIP_e5QMC9yK256iEv5HzlQNbIE',
    appId: '1:926948973737:ios:e037e6e2c72e3ca0daddb8',
    messagingSenderId: '926948973737',
    projectId: 'history-950d8',
    storageBucket: 'history-950d8.firebasestorage.app',
    iosBundleId: 'com.example.whatsappClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8LhjYHgce4iaXMxvzoDYD8D_N4XPUwaM',
    appId: '1:926948973737:web:99724dfd842b5a7fdaddb8',
    messagingSenderId: '926948973737',
    projectId: 'history-950d8',
    authDomain: 'history-950d8.firebaseapp.com',
    storageBucket: 'history-950d8.firebasestorage.app',
    measurementId: 'G-PER4ZCEPWE',
  );

}